# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = uwsm-app -- firefox-developer-edition

unbind = SUPER, B
unbind = SUPER SHIFT ,B
unbind = SUPER M
unbind = SUPER SHIFT, P

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, P, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT, S, Steam, exec, omarchy-launch-or-focus steam

# Open Godot
bindd = SUPER SHIFT, G, Godot, exec, omarchy-launch-or-focus "~/mfocus/Programming/Godot_v4.6.1.x86_64"

# Proton mail
bindd = SUPER SHIFT, E, Proton Mail, exec, omarchy-launch-webapp "https://mail.proton.me/u/0/inbox"
