monitor=DP-2,2560x1440@240,auto,1.25


### --- Browser (Workspace 1) ---
windowrule {
    name = browser-to-workspace-1
    match:class = ^chromium$
    workspace = 1
}

### --- Steam (Workspace 4) ---
windowrule {
    name = steam-ui
    match:class = ^steam$
    match:title = ^Steam*
    tile = true
    workspace = 4
    maximize = on
}

windowrule {
    name = steam-popups
    match:class = ^steam$
    match:title = ^(?!Steam).*
    float = on
}

### --- Games (Workspace 5) ---
# Steam / Proton games (float + fullscreen)
windowrule {
    name = steam-games
    match:class = ^steam_app_.+$
    float = on
    fullscreen = on
    workspace = 5
}
windowrule {
    name = steam-proton-games
    match:class = ^steam_proton_.+$
    float = on
    fullscreen = on
    workspace = 5
}

# Heroic & Lutris
windowrule {
    name = heroic-games
    match:class = ^heroic$
    float = on
    workspace = 5
}
windowrule {
    name = lutris-games
    match:class = ^lutris$
    float = on
    workspace = 5
}

### --- Spotify (Workspace 6) ---
windowrule {
    name = spotify-workspace-6
    match:class = ^spotify$
    workspace = 6
}

# Godot
windowrule {
    name = godot-workspace-3
    match:class = ^Godot$
    workspace = 3
}
